#!/bin/bash

# Mount glusterfs volume
loop=0
while [ loop -eq 0 ] do
	mount -t glusterfs storage:${GLUSTER_VOLUME} /home/git/data
	if [ $? -eq 0 ] then
		echo "Glusterfs volume is mounted in /home/git/data"
		loop=1
	else
		echo "There are some problem when try to mount Glusterfs volume. Are you sure you have linked gluster server with this container and have colled the link as 'storage' ? I will try again in 60s."
		sleep 60
	fi
done

exec /sbin/entrypoint.sh app:start
